name: Test site for publicly known JS vulnerabilities

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Test for public JavaScript library vulnerabilities
        uses: lirantal/is-website-vulnerable@main
        with:
          scan-url: https://yceffort.kr
